#!/usr/bin/env bash

CURRENT_DIR="$(dirname $(realpath $0))"

create_link() {
  if [ -f $CURRENT_DIR/$1 ]; then
    rm $HOME/$1
    ln -s $CURRENT_DIR/$1 $HOME/$1
  fi
}

create_links() {
  mkdir -p $HOME/$1

  FILES_DIR=$CURRENT_DIR/$1

  for file in $FILES_DIR/*; do
    FILE="$1/$(basename $file)"

    if [ -f $file ]; then
      create_link $FILE
    fi
  done
}

create_link .bashrc
create_link .bash_aliases
create_link .gitconfig
create_links .local/bin
