[window]
title = "Alacritty"
dynamic_title = false

[env]
TERM = "xterm-256color"

[cursor]
style = "Beam"

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
size = 14

[colors.normal]
black = "#121212"
red = "#ff6961"
green = "#77dd77"
yellow = "#fffacd"
blue = "#42a5f5"
magenta = "#f49ac2"
cyan = "#b4fffa"
white = "#faf8f6"

[colors.bright]
black = "#121212"
red = "#ff6961"
green = "#77dd77"
yellow = "#fffacd"
blue = "#42a5f5"
magenta = "#f49ac2"
cyan = "#b4fffa"
white = "#faf8f6"

[colors.primary]
foreground = "#d8d8d8"
background = "#000000"
dim_foreground = "#212121"
bright_foreground = "#ffffff"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"