#!/usr/bin/env bash


BIN_DIRS=(
	$HOME/.local/bin
	$HOME/.bun/bin
	$HOME/.cargo/bin
	${GOPATH:-$HOME/go}/bin
	$PNPM_HOME
	/opt/nvim/bin
)

for bin_dir in "${BIN_DIRS[@]}"; do
    if [ -d ":$bin_dir:" ] && [[ "" != *":$bin_dir:"* ]]; then 
	export PATH="$bin_dir:$PATH"
    fi
done

IFS=":"
BIN_DIRS_STRING=${BIN_DIRS[*]}
unset IFS

export PATH="$PATH:$BIN_DIRS_STRING"

if [ -d /opt/nvim ]; then
    export PATH="/opt/nvim/bin:$PATH"
fi
