context.modules = [
	{
		name = libpipewire-module-loopback
		args = {
			node.name = "virtual_master_device"
			node.description = "Master"
			capture.props = {
				node.name = "virtual_sink_master"
				media.class = "Audio/Sink"
			}
			playback.props = {
				node.target = "~alsa_output.*"
			}
		}
	},
	{
		name = libpipewire-module-loopback
		args = {
			node.name = "virtual_primary_device"
			node.description = "Primary"
			capture.props = {
				node.name = "virtual_sink_primary"
				media.class = "Audio/Sink"
			}
			playback.props = {
				node.target = "virtual_sink_master"
			}
		}
	},
	{
		name = libpipewire-module-loopback
		args = {
			node.name = "virtual_chat_device"
			node.description = "Chat"
			capture.props = {
				node.name = "virtual_sink_chat"
				media.class = "Audio/Sink"
			}
			playback.props = {
				node.target = "virtual_sink_master"
			}
		}
	},
	{
		name = libpipewire-module-loopback
		args = {
			node.name = "virtual_media_device"
			node.description = "Media"
			capture.props = {
				node.name = "virtual_sink_media"
				media.class = "Audio/Sink"
			}
			playback.props = {
				node.target = "easyeffects_sink"
				node.dont-fallback = false
			}
		}
	}
]
