general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 300 # 5 minutes
    on-timeout = loginctl lock-session
}

listener {
    timeout = 570 # 30 seconds before 10 minutes
    on-timeout = notify-send --hint=boolean:transient:true -t 2000 "System suspending in 30 seconds"
    on-resume = notify-send --hint=boolean:transient:true -t 2000 "System suspend cancelled"
}

listener {
    timeout = 600 # 10 minutes
    on-timeout = systemctl suspend
}
