general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 270
    on-timeout = notify-send --hint=boolean:transient:true -t 2000 "Screen lock activating in 30 seconds"
    on-resume = notify-send --hint=boolean:transient:true -t 2000 "Screen lock activation cancelled"
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
}
